aimclub/GOLEM

golem/metrics/mmd.py
Заменен тип float на float64. После этого пример заработал
=> [mmd] Change float to float64

golem/core/dag/graph.py, golem/core/dag/graph_delegate.py, golem/core/dag/linked_graph.py, golem/core/optimisers/advisor.py, golem/core/optimisers/genetic/operators/base_mutations.py, test/unit/dag/test_graph.py, test/unit/dag/test_graph_operator.py
Previously they were automatically preserved because parents were always reconnected to children.
This change is backward compatible except for 1 rename (`RemoveType.node_only -> RemoveType.node_rewire`), no current behavior is altered.
Related to #69 where cycles that appeared in graph precluded optimization from  removing accidental cycles.
=> Fix delete_node to allow breaking cycles in graphs.

docs/source/api/tuning.rst, golem/core/tuning/hyperopt_tuner.py, golem/core/tuning/iopt_tuner.py, golem/core/tuning/search_space.py, golem/core/tuning/sequential.py, golem/core/tuning/simultaneous.py, golem/core/tuning/tuner_interface.py, requirements.txt, test/unit/tuning/test_tuning.py
- Adds new `IOptTuner` 
- New base class for tuners is introduced `BaseTuner` 
- The way search space is defined is changed
Concerns:
- inconvenient way to define search space. IOpt needs this division on descrete and continuous parameters, which requires additional info in search space
- IOpt does not support nested search space, which can be nessesary for some operations optimisation in FEDOT (https://github.com/aimclub/FEDOT/blob/master/fedot/core/pipelines/tuning/search_space.py#L137-L154)
IOpt supports only continuous parameters, so discrete ones are optimised as continuous and are rounded. Also there is no support for timeout and initial point.
Despite this, on classification task IOpt oftenly outperformes huperopt (but also usually takes more time, especially when search space has …
=> Add IOpt tuner

golem/core/optimisers/opt_history_objects/opt_history.py, golem/serializers/coders/opt_history_serialization.py, golem/visualisation/opt_history/arg_constraint_wrapper.py, golem/visualisation/opt_history/fitness_box.py, golem/visualisation/opt_history/fitness_line.py, golem/visualisation/opt_history/operations_kde.py, golem/visualisation/opt_history/utils.py, golem/visualisation/opt_viz_extra.py, test/integration/test_quality_improvement.py, test/unit/optimizers/test_composing_history.py
* Turned logger into property, since logger is not serialized and thus not recreated during deseralization.
* Renamed `OptHistory.individuals` -> `generations`, added deprecation warning for the older variant.
=> Minor fixes in OptHistory

examples/synthetic_graph_evolution/experiment_setup.py, golem/core/optimisers/genetic/diversity.py, golem/visualisation/opt_history/diversity.py, golem/visualisation/opt_viz.py
Add 2 new kinds of plot for estimating diversity of populations based on OptHistory.
Done as additional functionality during work on #89 
Usage example:
```
history.show.diversity_population(save_path='diversity-dynamic.gif')  # for saving gif
history.show.diversity_line()  # for diversity line
```
2 examples: below for multi-objective optimization with 4 metrics at once: 
- static plot howing diversity during optimization;
- GIF plot showing metric distribution per each metric in population
=> Add new plots for population Diversity

.github/workflows/integration-build.yml, .github/workflows/notify.yml, README.rst, README_en.rst
- Added telegram notification if scheduled integration tests fail
- Renamed PR-related notification workflow
- Added small improvements to the notification messages (the repo name, links embedded in text, etc.)
- Fixed badge link in `README.rst` and `README_en.rst`
=> Add notification after integration tests & fix the workflow badge

.github/workflows/integration-build.yml
One part of the complex condition wasn't tested, since the scheduled workflow runs on the main branch only.
After merge to main, the full condition always returns true.
Most likely, the condition is interpreted as a literal, not as an expression.
=> Hotfix condition on telegram notification of integration tests

examples/molecule_search/mol_adapter.py, golem/core/adapter/nx_adapter.py, golem/core/dag/graph.py, golem/core/dag/graph_utils.py, golem/core/dag/linked_graph.py, golem/core/dag/verification_rules.py, golem/core/optimisers/genetic/operators/base_mutations.py, golem/core/optimisers/genetic/operators/crossover.py, golem/metrics/edit_distance.py, test/integration/test_cycled_graph_evolution.py, test/unit/dag/test_graph_operator.py, test/unit/dag/test_graph_utils.py, test/unit/dag/test_graph_verification.py, test/unit/optimizers/gp_operators/test_mutation.py, test/unit/utils.py
Some problems with cycled graphs evolution was soleved:
- `descriptive_id` construction
- `distance_to_root_level` now returns -1 if graph has cycles
- `node_depth` returns -1 if graph has cycles
- `graph.depth` is equal -1 if graph is cycled
Some operators don't work for cycled graphs:
- `CrossoverTypesEnum.one_point`
- `CrossoverTypesEnum.subtree`
- `MutationTypesEnum.tree_growth`
- `MutationTypesEnum.growth`
- `MutationTypesEnum.local_growth`
- `MutationTypesEnum.reduce`
The reason - these crossovers use the logic of node depth and distance to primary level which can not be applyed to graphs with cycles. Also we need ordered subnodes hierarchy for subtree removal that can't be used for cycled graphs. Mutations are not available due to need to calculate distance to root level. …
=> Fix recursions for cycled graphs 

golem/core/dag/graph_utils.py, golem/core/dag/linked_graph.py, test/unit/dag/test_graph_utils.py, test/unit/utils.py
Node depth was not working correctly for graphs with the following structure (decompose node in FEDOT)
Also `update_node` was not working correctly because only adding node to `self._nodes` does not add nodes predecessors to `graph.nodes`
=> Fix node_depth

golem/core/optimisers/genetic/gp_optimizer.py, golem/core/optimisers/genetic/gp_params.py, golem/core/optimisers/genetic/parameters/mutation_prob.py, golem/core/optimisers/genetic/parameters/population_size.py, test/integration/test_genetic_schemes.py
The problem with `parameter_free` genetic scheme was with mutation probability. In some cases mutation probability was set to zero so there were no way to produce next generation because there were no crossover.
Added:
- minimal value for mutation probability
- minimal test for genetic schemes
Results of experiments for molecules on 5 trials for each scheme
=> Fix parameter free scheme

examples/molecule_search/mol_adapter.py, golem/core/adapter/adapter.py, golem/core/adapter/nx_adapter.py, golem/core/tuning/optuna_tuner.py, golem/core/tuning/tuner_interface.py, test/unit/adapter/graph_data.py, test/unit/adapter/test_adapter.py, test/unit/tuning/test_tuning.py
`BaseNetworkxAdapter` refactored to process parameters of graph nodes correctly.
Also:
- adapter now can restore a list of OptGraphs
- OptunaTuner saves study (g.e. to use it for visualisations via optuna)
=> Fix networkx adapter

examples/molecule_search/mol_advisor.py
Previously MolAdvisor allowed to delete a single atom from molecule which was leading to an empty graph.
=> MolAdvisor fix

examples/molecule_search/mol_adapter.py, examples/molecule_search/mol_graph.py, golem/core/adapter/nx_adapter.py, golem/core/optimisers/genetic/gp_operators.py, golem/core/optimisers/optimizer.py, test/integration/test_evolution_with crossover.py, test/integration/test_evolution_with_crossover.py, test/unit/adapter/graph_data.py, test/unit/adapter/test_adapter.py
Fixes:
- nx graph adaptation
- `structural_equivalent_nodes`
Adds test for evolution with crossover.
#206
=> Fix crossover

golem/core/optimisers/meta/surrogate_optimizer.py, golem/core/optimisers/populational_optimizer.py
The change uses cycle break instead of early return in optimizer. 
This allows to close the progress bar and to save the final choices to history.
=> Fix final choices saving in optimizers

golem/core/dag/graph.py, golem/visualisation/graph_viz.py, test/unit/visualisation/test_visualisation_utils.py
Solves #56 
Transferred scalable matplotlib graph visualization from other project.
Changes:
- Added parameter "fig_size"
- Added parameter "nodes_layout_function" that allows to use custom graph layouts
- Added parameter "node_names_placement" that accepts following options:
- 'auto' - If size of the nodes is less than 1000 px, their names are shown in the legend automatically
- 'nodes' - show node names strictly on top of the nodes
- 'legend' - show node names strictly in legend
- 'none' - do not show node names (but the appearance of the nodes is selected by 'auto' rule)
-  Added legend ordering by label
- Minor refactoring of GraphVisualizer
=> Scalable graph vizualization

golem/core/tuning/hyperopt_tuner.py, golem/core/tuning/iopt_tuner.py, golem/core/tuning/optuna_tuner.py, golem/core/tuning/sequential.py, golem/core/tuning/simultaneous.py, golem/core/tuning/tuner_interface.py, test/unit/tuning/test_tuning.py
All tuners now can except the same arguments. Also timer and check for possibility of tuning was added.
#232
=> Tuner interface update

golem/core/log.py, golem/core/optimisers/opt_history_objects/individual.py, test/unit/test_logger.py
- Create a method "log_or_raise" to replace the argument "raise if test"
- Write a test for this method
=> Fix "raise_if_test" behaviour

golem/core/tuning/hyperopt_tuner.py, test/unit/tuning/test_tuning.py
Monkey-patch the `hyperopt.hp.randint` near the definition of `HyperoptTuner`.
Makes it return an `int` instead of a `np.int64`.
=> Fix hyperopt.hp.randint

golem/core/tuning/optuna_tuner.py, test/unit/tuning/test_tuning.py
Minor fix for `OptunaTuner`: `early_stopping_iteration` is not applicable for multi-objective problem.
=> Remove callback

golem/core/optimisers/genetic/operators/base_mutations.py, golem/core/optimisers/genetic/operators/mutation.py, golem/core/optimisers/genetic/parameters/mutation_prob.py, golem/core/optimisers/random_graph_factory.py, test/integration/test_genetic_schemes.py, test/unit/optimizers/gp_operators/test_mutation.py, test/unit/optimizers/test_random_graph_factory.py
Changes:
- If mutation will be applied is decided outside of the retry loop. Previously we were shooting ourselves in the foot trying to defenetly apply a mutation while deciding to apply it with some probability in the loop.
- Also the choice of the mutation type is made outside the loop to collect proper experience for the agent (now the agent can know that the exact mutation type failed to apply to the specified graph).
- Negative reward in case of unsuccesfull mutation is registered only once after several attempt. It prevents the agent of being biased.
- Base mutations now try on different nodes to make any change which makes it possible to remove equality check in the mutation operator.
Proposed changes have shown better results on synthetic task for tree graph (random bandit).
Here …
=> Fix mutation operator

golem/core/optimisers/genetic/gp_params.py, golem/core/optimisers/genetic/operators/selection.py, test/unit/optimizers/gp_operators/test_selection.py
Now useres can set custom selection function of type `custom_selection(populattion: PopulationT, pop_size: int]) -> PopulationT`
#240
=> Add custom selection

other_requirements/molecules.txt
quick gensim dependency resolution regarding integration tests failure
[recent gensim fix](https://github.com/piskvorky/gensim/commit/ad68ee3f105fc37cf8db333bfb837fe889ff74ac)
=> fix: resolve gensim dependency on a specific commit

golem/core/tuning/hyperopt_tuner.py, golem/core/tuning/sequential.py, golem/core/tuning/simultaneous.py, golem/core/tuning/tuner_interface.py
Changes:
- `SequentialTuner` searches near initial parameters just like `SimultaneousTunes`
- `SequentialTuner` returnes the best obtained graph amonge ones obtained after each iteration of node tuning
=> Fix sequential

examples/molecule_search/experiment.py, golem/core/optimisers/adaptive/mab_agents/contextual_mab_agent.py, golem/core/optimisers/adaptive/mab_agents/mab_agent.py, golem/core/optimisers/genetic/operators/base_mutations.py, golem/core/optimisers/genetic/operators/mutation.py
- Mutation should be saved as a string to avoid problems with custom mutations serialisation
- Bandits should store arm action mapping accordingly: key should be a string
=> Fix adding mutation as parent operator

golem/core/tuning/iopt_tuner.py, golem/core/tuning/sequential.py, golem/core/tuning/tuner_interface.py, golem/metrics/edit_distance.py, setup.py
Additionally:
Closes #186, #267, #280
=> Fix timeout-related issues in tuners 
