.github/workflows/unit-build.yml
README.rst
codecov.yml
requirements.txt

Add github actions 

---

README.rst
examples/graph_model_optimization.py
examples/synthetic_graph_evolution/abstract_graph_search.py
golem/core/optimisers/archive/generation_keeper.py
golem/core/optimisers/genetic/gp_operators.py
golem/core/optimisers/genetic/operators/mutation.py
golem/core/optimisers/genetic/operators/operator.py
golem/core/optimisers/initial_graphs_generator.py
golem/core/optimisers/optimizer.py
golem/core/optimisers/random/random_mutation_optimizer.py
golem/core/optimisers/random/random_search.py
golem/core/optimisers/random_graph_factory.py
requirements.txt
test/unit/optimizers/test_composing_history.py
test/unit/optimizers/test_initial_population_generator.py
test/unit/optimizers/test_random_graph_factory.py

RandomSearchOptimizer and RandomMutationSearchOptimizer are added. 
BaseRandomOptGraphFactory is implemented to allow users to customise random graph generation.

Add other optimizers

---

examples/synthetic_graph_evolution/abstract_graph_search.py
examples/synthetic_graph_evolution/graph_metrics.py
examples/synthetic_graph_evolution/utils.py
golem/core/optimisers/archive/generation_keeper.py

Better visualisations & other kidns of optimizers are added.
Also new metric based on node degress.

Improvements  for usability to synthethic search example

---

golem/core/optimisers/genetic/parameters/population_size.py

fix pop size

---

README.rst

Text of the section actualized.

README section "Supported by" modified

---

examples/synthetic_graph_evolution/utils.py
golem/core/optimisers/objective/objective.py
golem/core/optimisers/opt_history_objects/opt_history.py
golem/core/optimisers/optimizer.py
golem/serializers/coders/opt_history_serialization.py
golem/serializers/serializer.py
test/unit/optimizers/test_composing_history.py

Add ObjectiveInfo to OptHistory

---

golem/core/dag/graph.py
golem/core/log.py
golem/core/optimisers/archive/individuals_containers.py
golem/core/optimisers/genetic/evaluation.py
golem/core/optimisers/opt_history_objects/individual.py
golem/core/optimisers/optimization_parameters.py
golem/core/optimisers/populational_optimizer.py
golem/core/optimisers/random/random_search.py
golem/core/tuning/tuner_interface.py
test/unit/optimizers/test_evaluation.py

Changes from fedot:
- https://github.com/aimclub/FEDOT/commit/c206947ebadea0295fcf9cefe5dd7b1e2888091a
- https://github.com/aimclub/FEDOT/commit/3deb3e36aac491d86c9fa1d0c1b98d7a3d5b0fd3

Add latest changes from fedot

---

golem/core/optimisers/archive/generation_keeper.py
golem/core/optimisers/genetic/evaluation.py
golem/core/optimisers/genetic/parameters/population_size.py
golem/core/optimisers/populational_optimizer.py
golem/core/utilities/data_structures.py
golem/core/utilities/sequence_iterator.py
test/unit/optimizers/gp_operators/test_population_size.py
test/unit/optimizers/test_composing_history.py

Unstable population size & related eval problems

---

golem/core/log.py
test/unit/test_logger.py

logger minor fix

---

examples/synthetic_graph_evolution/abstract_graph_search.py
golem/core/dag/graph_utils.py
golem/core/dag/linked_graph.py
golem/core/dag/linked_graph_node.py
golem/core/dag/verification_rules.py
golem/core/optimisers/genetic/gp_optimizer.py
golem/core/optimisers/genetic/gp_params.py
golem/core/optimisers/genetic/operators/base_mutations.py
golem/core/optimisers/genetic/operators/mutation.py
golem/serializers/coders/graph_node_serialization.py
test/unit/dag/test_graph.py
test/unit/optimizers/gp_operators/test_mutation.py
test/unit/optimizers/test_composing_history.py
test/unit/test_custom.py

- Now Mutation operator is agnostic of specific mutations that are used by it
- Default mutations are in a separate file `base_mutations`
- Several fixes for mutations, mostly related to cyclic graphs

Mutation fixes: separate specific mutations from operator

---

README.rst
README_en.rst

Badges for funders (ITMO, SAI) and gitlab mirror added.

Add ITMO-related badges

---

golem/core/optimisers/genetic/operators/base_mutations.py

single_drop_mutation fix

---

examples/synthetic_graph_evolution/abstract_graph_search.py
examples/synthetic_graph_evolution/experiment.py
examples/synthetic_graph_evolution/generators.py
examples/synthetic_graph_evolution/graph_search.py
examples/synthetic_graph_evolution/tree_search.py
examples/synthetic_graph_evolution/utils.py
golem/core/adapter/nx_adapter.py
golem/core/optimisers/genetic/gp_operators.py
golem/core/optimisers/objective/objective.py
golem/metrics/edit_distance.py
golem/metrics/graph_metrics.py
requirements.txt
test/integration/test_quality_improvement.py
test/integration/test_structure_search.py
test/unit/optimizers/gp_operators/test_gp_operators.py

- Refactor experiment setup for synthetic search
- Add new dependency for fast Edit Distance computation on `zss` package
- Implement new example
Closes #38 
UPD: provides temporary fix for #63

Add example for synthetic tree evolution

---

examples/surrogate/surrogate_example.py
examples/synthetic_graph_evolution/graph_search.py
golem/core/optimisers/genetic/evaluation.py
golem/core/optimisers/meta/surrogate_evaluator.py
golem/core/optimisers/meta/surrogate_model.py
golem/core/optimisers/meta/surrogate_optimizer.py
test/unit/optimizers/test_evaluation.py

Surrogate optimizer, evaluator and model were added.

Add surrogate optimizer

---

.github/workflows/manual-build.yml
docs/source/conf.py
setup.py
test/integration/test_structure_search.py

And enable integration tests on 'stable' branch

Release: upd version on main

---

examples/adaptive_optimizer/utils.py

Fixed stackplot for usual line plot

Fix action values viz plot (for adaptive mutations)

---

.github/workflows/integration-build.yml
README.rst
README_en.rst

Make it run every day, add example requirements

Update integration build workflow

---

test/integration/test_structure_search.py

Fix integration test for struct_search

---

golem/metrics/edit_distance.py
test/integration/test_structure_search.py

Increase the indulgence for the test with structure search and add a new one concerned with the search of graph with specified size

fix integration test

---

docs/source/api/tuning.rst
golem/core/optimisers/populational_optimizer.py
golem/core/tuning/iopt_tuner.py
golem/core/tuning/optuna_tuner.py
golem/core/tuning/sequential.py
golem/core/tuning/simultaneous.py
golem/core/tuning/tuner_interface.py
requirements.txt
test/unit/tuning/test_tuning.py
test/unit/utils.py

New tuner based on optuna lib is added which enables multiobjective optimisations. Tests comparing the new tuner with others have not yet been conducted.
#112

Add OptunaTuner

---

golem/metrics/edit_distance.py
test/integration/test_structure_search.py

Test were failing because of incorrect metrics
Test status: https://github.com/aimclub/GOLEM/actions/runs/5541090394

Fix integation test (v4)

---

test/unit/dag/test_graph.py

Added one test to check #32; all works.

Add test for graph.delete_node

---

golem/core/optimisers/genetic/operators/reproduction.py

Fixes this issue from comment https://github.com/aimclub/FEDOT/issues/1110#issuecomment-1663983354#148 
Thanks @IIaKyJIuH for noticing

Fix corner case when pop_size=1 in Reproduction

---

golem/core/optimisers/populational_optimizer.py

Previously progress bar was freezing at the first iteration. Now it is working as expected.

Fix progress bar

---

golem/core/optimisers/genetic/evaluation.py
test/unit/optimizers/test_evaluation.py

Fix for https://github.com/aimclub/FEDOT/issues/1170.

Add checks to `determine_n_jobs` and add test for it

---

examples/molecule_search/experiment.py

Fix MultipleFitnessLines usage

Fix molecule example

---

golem/core/optimisers/adaptive/neural_mab.py
other_requirements/adaptive.txt

Changed version of `torch `from `1.8.0 `to `2.0.0` and added some useful comments for NeuralMABs

Integration tests fix

---

golem/core/optimisers/populational_optimizer.py

PR to fixs bug reported by @MangaBoba -- issues #216

Fix reported bugs

---

golem/core/optimisers/genetic/operators/mutation.py

Fix setting parent operation in mutation

---

golem/core/optimisers/genetic/operators/inheritance.py

Resolves #266 (list conversion is considered the only acceptable fix — see discussion there)

Fix sequence sum in steady-state inheritance

---

requirements.txt

Pin scipy versions to release FEDOT in PyPi with gensim.
https://github.com/aimclub/FEDOT/pull/1287

Pin scipy versions to fix gensim in fedot

---

.github/workflows/notify.yml
test/integration/test_genetic_schemes.py

Fix for `test/integration/test_genetic_schemes.py`: added random seed for stability

Fix test_genetic_schemes: set random seed for stability
